# fly.toml app configuration file generated for via-bill-scanner on 2026-04-15T19:27:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'via-bill-scanner'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  GOMEMLIMIT = '200MiB'

[[mounts]]
  source = 'pb_data'
  destination = '/app/pb_data'

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
